version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build Solution
          command: cd ~/repo/src && dotnet build
      - run:
          name: Test
          command: |
            cd ~/repo/src/ODataHttpClient.Tests
            dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
            bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
            - ~/repo
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
  push_preview:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            cd ~/repo/src/ODataHttpClient
            version=$(echo $CIRCLE_TAG | sed 's/v//' -r)
            sed -i -e "s/[$]version[$]/$version/g" ./ODataHttpClient.nuspec
            dotnet pack -c Release
            dotnet nuget push ./bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_TOKEN
  push:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            cd ~/repo/src/ODataHttpClient
            version=$(echo $CIRCLE_TAG | sed 's/v//' -r)
            sed -i -e "s/[$]version[$]/$version/g" ./ODataHttpClient.nuspec
            dotnet pack -c Release
            dotnet nuget push ./bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_TOKEN
workflows:
  version: 2
  default:
    jobs:
      - build
  publish:
    jobs:
      - build:
          filters:
            tags: 
              only: /.*/
            branches:
              ignore: /.*/
      - push_preview:
          requires:
            - build
          filters:
            tags: 
              only: /^v[0-9]+(\.[0-9]+)*-.+$/
            branches:
              ignore: /.*/
      - push:
          requires:
            - build
          filters:
            tags: 
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
